substitutions:
  device_id: "3"

packages:
  common: !include common.yaml

light:
  - platform: monochromatic
    name: Desk LED Strip Left
    id: light_ch1
    output: output_ch1
    effects:
      flicker:
