esphome:
  name: esp32-c6-fusb302-esp-idf-test
  on_boot:
    - delay: 500ms
    - logger.log:
        format: "Starting PD negotiation"
        level: WARN
    - fusb302.start_power_negotiation:
        id: fusb302_id

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  framework:
    type: esp-idf
    version: 5.1.2
    platform_version: 6.5.0

i2c:
  - id: i2c_bus_fusb302
    scl: 23
    sda: 22

logger:
  level: INFO

fusb302:
  id: fusb302_id
  i2c_id: i2c_bus_fusb302
  interrupt_pin: 21
  voltage: 11000 mV
  current: 1000 mA
  start_power_negotiation_on_boot: false
  on_pd_negotiation_success:
    - lambda: |-
        ESP_LOGW("fusb302_trigger", "PD negotiation success outcome: %d", success);
  on_pd_negotiation_failure:
    then:
      - lambda: |-
          ESP_LOGW("fusb302_trigger", "PD negotiation failure outcome: %d", success);
