esphome:
  name: rp2040-fusb302-test
  friendly_name: rp2040 FUSB302 Test
  on_boot:
    - delay: 500ms
    - logger.log:
        format: "Will start PD negotiation"
        level: WARN
    # - fusb302.start_power_negotiation:
    #     id: fusb302_id

rp2040:
  board: rpipicow
  framework:
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# packages:
#   wifi: !include ../common/wifi.yaml

i2c:
  - id: i2c_bus_fusb302
    sda: 16
    scl: 17

logger:
  level: DEBUG

output:
  - platform: gpio
    pin:
      number: 32
      mode: output
    id: LED

fusb302:
  id: fusb302_id
  i2c_id: i2c_bus_fusb302
  interrupt_pin: 15
  voltage: 11000 mV
  current: 1000 mA
  on_pd_negotiation_success:
    - lambda: |-
        ESP_LOGW("fusb302_trigger", "PD negotiation success outcome: %d", success);
    - output.turn_on: LED
  on_pd_negotiation_failure:
    then:
      - lambda: |-
          ESP_LOGW("fusb302_trigger", "PD negotiation failure outcome: %d", success);
