substitutions:
  device_id: "4"

packages:
  common: !include common.yaml
  oled: !include common-oled.yaml
  wifi: !include common-wifi.yaml

logger:
  level: INFO

fusb302:
  id: fusb302_id
  voltage: 12000 mV
  current: 1000 mA

light:
  - platform: monochromatic
    name: Light Channel 1
    id: light_ch1
    output: output_ch1
    effects:
      flicker:
