substitutions:
  gimme_danger_device_id: "1"

packages:
  gimme_danger: !include common/gimme-danger.yaml
  oled: !include common/oled.yaml
  wifi: !include common/wifi.yaml

fusb302:
  id: fusb302_id
  voltage: 10500 mV
  current: 1000 mA

light:
  - platform: rgbw
    name: LED Strip
    red: output_ch1
    green: output_ch2
    blue: output_ch3
    white: output_ch4
    effects:
      flicker:
