substitutions:
  gimme_danger_device_id: "4"

packages:
  gimme_danger: !include common/gimme-danger.yaml
  oled: !include common/oled.yaml
  wifi: !include common/wifi.yaml

fusb302:
  id: fusb302_id
  voltage: 12000 mV
  current: 1000 mA

light:
  - platform: monochromatic
    name: Light Channel 1
    id: light_ch1
    output: output_ch1
    effects:
      flicker:
